import {
  CHEM_PROCESSES,
  CONTACT_CHANNELS,
  FILM_FORMATS,
  labPath,
  type ContactChannel,
  type FilmFormat,
  type HistoryChange,
  type LabStatus,
} from "@/lib/labs/paths";
import type { LabDetail } from "@/lib/queries/labs";

/**
 * The form's own model of a lab, and the diff it produces.
 *
 * This is the half of B4 that has to be right. The form submits leaf changes,
 * not a document (lib/labs/paths.ts), so this file is where a contributor's
 * typing becomes the set of leaves they actually touched — and anything it emits
 * that they did not change silently reverts somebody else's work.
 *
 * Every field is held as a string, the way a form holds it. Parsing happens at
 * diff time, once, so `"180"` and `" ฿180 "` produce the same leaf and neither
 * produces a change when the stored value is already 180. A model that stored
 * numbers would have to decide what an empty input means on every keystroke;
 * this one decides it once, here.
 *
 * Pure and free of React on purpose: the diff is the thing worth testing, and a
 * test should not have to render anything to reach it.
 */

export type DraftDay =
  { closed: true } | { closed: false; open: string; close: string };

export type DraftContact = {
  /** Generated by the form, so add, edit and remove are one shape. */
  id: string;
  channel: ContactChannel;
  value: string;
};

export type DraftCustom = { id: string; label: string; note?: string };

export type DraftStock = {
  filmStockId: string;
  name: string;
  formats: FilmFormat[];
};

/** One cell of the pricing matrix, as typed rather than as stored. */
export type DraftCell = {
  /** "180", "฿180", "" — parsed at diff time. */
  price: string;
  /** "2" or "2-4" days. One input, because that is what the prototype draws. */
  turnaround: string;
};

export type LabDraft = {
  nameEn: string;
  nameTh: string;
  areaEn: string;
  areaTh: string;
  street: string;
  landmarkNote: string;
  status: LabStatus;
  statusNote: string;
  location: { lat: number; lng: number } | null;
  /** Seven days, or null when nobody has entered a schedule at all. */
  hours: DraftDay[] | null;
  processes: Record<string, boolean>;
  scanners: Record<string, boolean>;
  /** Keyed `${process}.${format}`. */
  pricing: Record<string, DraftCell>;
  /** Curated services, keyed by catalog key. */
  services: Record<string, { on: boolean; note: string }>;
  customServices: DraftCustom[];
  /** Curated supplies, keyed by catalog key. */
  supplies: Record<string, boolean>;
  customSupplies: DraftCustom[];
  contacts: DraftContact[];
  stock: DraftStock[];
};

export const CELL_KEYS = CHEM_PROCESSES.flatMap((process) =>
  FILM_FORMATS.map((format) => ({
    process,
    format,
    key: `${process}.${format}`,
  })),
);

// ---------------------------------------------------------------------------
// Parsing what a person types
// ---------------------------------------------------------------------------

/** `" ฿1,180 "` → 1180. Anything that is not a number is "not entered". */
export function parsePrice(input: string): number | null {
  const cleaned = input.replace(/[฿,\s]/g, "");
  if (cleaned === "") return null;
  const value = Number(cleaned);
  return Number.isFinite(value) && value >= 0 ? value : null;
}

export function formatPrice(value: number | null): string {
  return value === null ? "" : String(value);
}

/**
 * `"2"` → 2 days. `"2-4"` → 2 to 4.
 *
 * One input rather than two number boxes, because the prototype draws one and
 * because "2-4" is how a person says it. An en dash counts: it is what a phone
 * keyboard and a paste from a website both produce.
 */
export function parseTurnaround(input: string): {
  min: number | null;
  max: number | null;
} {
  const cleaned = input.replace(/\s|days?/gi, "");
  if (cleaned === "") return { min: null, max: null };

  const [first, second] = cleaned.split(/[-–—]/);
  const min = toDay(first);
  const max = second === undefined ? null : toDay(second);
  return min === null ? { min: null, max: null } : { min, max };
}

function toDay(part: string | undefined): number | null {
  if (!part) return null;
  const value = Number(part);
  return Number.isInteger(value) && value > 0 ? value : null;
}

export function formatTurnaround(
  min: number | null,
  max: number | null,
): string {
  if (min === null) return "";
  return max === null || max === min ? String(min) : `${min}-${max}`;
}

/** An empty box is absent, never `""` — the grammar refuses the other spelling. */
function textOrNull(value: string): string | null {
  const trimmed = value.trim();
  return trimmed === "" ? null : trimmed;
}

// ---------------------------------------------------------------------------
// Reading a lab into the form
// ---------------------------------------------------------------------------

/** An empty draft, for Add Lab. */
export function emptyDraft(): LabDraft {
  return {
    nameEn: "",
    nameTh: "",
    areaEn: "",
    areaTh: "",
    street: "",
    landmarkNote: "",
    status: "open",
    statusNote: "",
    location: null,
    hours: null,
    processes: {},
    scanners: {},
    pricing: {},
    services: {},
    customServices: [],
    supplies: {},
    customSupplies: [],
    contacts: [],
    stock: [],
  };
}

/**
 * The lab as the form holds it.
 *
 * Called once to seed the fields and once more to keep as the baseline the diff
 * is taken against, so what is compared is two drafts rather than a draft and a
 * database row. That matters: `"180"` versus `180` is a formatting question, and
 * answering it in two places is how a form starts reporting changes nobody made.
 */
export function draftFromLab(lab: LabDetail): LabDraft {
  const pricing: Record<string, DraftCell> = {};
  for (const cell of lab.pricing) {
    pricing[`${cell.process}.${cell.format}`] = {
      price: formatPrice(cell.priceThb),
      turnaround: formatTurnaround(cell.turnaroundMinD, cell.turnaroundMaxD),
    };
  }

  const services: Record<string, { on: boolean; note: string }> = {};
  const customServices: DraftCustom[] = [];
  for (const row of lab.services) {
    if (row.custom) {
      customServices.push({
        id: row.id!,
        label: row.customLabel ?? "",
        note: row.note ?? "",
      });
    } else if (row.key) {
      services[row.key] = { on: row.offered, note: row.note ?? "" };
    }
  }

  const supplies: Record<string, boolean> = {};
  const customSupplies: DraftCustom[] = [];
  for (const row of lab.supplies) {
    if (row.key) supplies[row.key] = true;
    else customSupplies.push({ id: row.id, label: row.customLabel ?? "" });
  }

  return {
    nameEn: lab.nameEn,
    nameTh: lab.nameTh ?? "",
    areaEn: lab.areaEn ?? "",
    areaTh: lab.areaTh ?? "",
    street: lab.street ?? "",
    landmarkNote: lab.landmarkNote ?? "",
    status: lab.status,
    statusNote: lab.statusNote ?? "",
    location: { lat: lab.lat, lng: lab.lng },
    hours: lab.hours ? lab.hours.map(toDraftDay) : null,
    processes: Object.fromEntries(lab.processes.map((p) => [p, true])),
    scanners: Object.fromEntries(lab.scanners.map((s) => [s, true])),
    pricing,
    services,
    customServices,
    supplies,
    customSupplies,
    contacts: lab.contacts.map((c) => ({ ...c })),
    stock: lab.stock.map((s) => ({
      filmStockId: s.filmStockId,
      name: s.name,
      formats: [...s.formats],
    })),
  };
}

function toDraftDay(
  day: LabDetail["hours"] extends (infer T)[] | null ? T : never,
): DraftDay {
  return day.closed
    ? { closed: true }
    : { closed: false, open: day.open, close: day.close };
}

/** Seven closed days — what an untouched week becomes the moment one is edited. */
export function blankWeek(): DraftDay[] {
  return Array.from({ length: 7 }, () => ({ closed: true }) as DraftDay);
}

// ---------------------------------------------------------------------------
// The diff
// ---------------------------------------------------------------------------

/**
 * Two drafts in, the leaves that differ out.
 *
 * The contract with lib/labs/paths.ts is exact: one entry per leaf, `from` and
 * `to` typed as that leaf allows, and nothing emitted for a field the
 * contributor did not touch. A change that is not here cannot be written, and a
 * change that is here wrongly overwrites somebody else's.
 */
export function diffDraft(
  initial: LabDraft,
  current: LabDraft,
): HistoryChange[] {
  const changes: HistoryChange[] = [];
  const push = (path: string, from: unknown, to: unknown) => {
    if (JSON.stringify(from) !== JSON.stringify(to))
      changes.push({ path, from, to });
  };

  // Scalars.
  push("name_en", initial.nameEn.trim(), current.nameEn.trim());
  for (const field of [
    "nameTh",
    "areaEn",
    "areaTh",
    "street",
    "landmarkNote",
    "statusNote",
  ] as const) {
    push(
      SCALAR_PATHS[field],
      textOrNull(initial[field]),
      textOrNull(current[field]),
    );
  }
  push("status", initial.status, current.status);

  // The pin. One leaf, never two — half a coordinate pair is a lab in the sea.
  push("location", initial.location, current.location);

  diffHours(initial, current, push);
  diffProcesses(initial, current, changes, push);
  diffScanners(initial, current, push);
  diffPricing(initial, current, push);
  diffServices(initial, current, push);
  diffSupplies(initial, current, push);
  diffContacts(initial, current, push);
  diffStock(initial, current, push);

  return changes;
}

type Push = (path: string, from: unknown, to: unknown) => void;

const SCALAR_PATHS = {
  nameTh: "name_th",
  areaEn: "area_en",
  areaTh: "area_th",
  street: "street",
  landmarkNote: "landmark_note",
  statusNote: "status_note",
} as const;

/**
 * Hours, day by day.
 *
 * A week that did not exist is compared against seven closed days rather than
 * against nothing, because that is what the database will materialise
 * (`labs_hours_shape` allows 0 or 7 entries and nothing between). Comparing
 * against null instead would emit `closed: null → true` for six untouched days.
 */
function diffHours(initial: LabDraft, current: LabDraft, push: Push): void {
  if (current.hours === null) return;
  const before = initial.hours ?? blankWeek();
  const wasUnset = initial.hours === null;

  current.hours.forEach((day, index) => {
    const was = before[index];

    // An untouched day in a week that never existed is not a change to report:
    // the database is about to write it either way, and seven "closed" lines in
    // the log for one edited Tuesday is noise nobody can read past.
    if (wasUnset && day.closed) return;

    push(labPath.hours(index, "closed"), was.closed, day.closed);
    push(
      labPath.hours(index, "open"),
      was.closed ? null : was.open,
      day.closed ? null : day.open,
    );
    push(
      labPath.hours(index, "close"),
      was.closed ? null : was.close,
      day.closed ? null : day.close,
    );
  });
}

/**
 * Processes, and the pricing a dropped one takes with it.
 *
 * `lab_pricing`'s foreign key cascades, so turning a process off destroys its
 * cells. The form is the only place that knows both that the process is going
 * and what was in those cells, so it is the only place that can record it.
 * `applyLabChanges` refuses the save otherwise — deliberately, because a log
 * that does not mention four vanished prices is a log that lies.
 */
function diffProcesses(
  initial: LabDraft,
  current: LabDraft,
  changes: HistoryChange[],
  push: Push,
): void {
  for (const process of CHEM_PROCESSES) {
    const was = initial.processes[process] === true;
    const now = current.processes[process] === true;
    if (was === now) continue;

    push(labPath.process(process), was, now);
    if (now) continue;

    for (const format of FILM_FORMATS) {
      const cell = initial.pricing[`${process}.${format}`];
      if (!cell) continue;
      const price = parsePrice(cell.price);
      const { min, max } = parseTurnaround(cell.turnaround);
      if (price !== null)
        changes.push({
          path: labPath.pricing(process, format, "price_thb"),
          from: price,
          to: null,
        });
      if (min !== null)
        changes.push({
          path: labPath.pricing(process, format, "turnaround_min_d"),
          from: min,
          to: null,
        });
      if (max !== null)
        changes.push({
          path: labPath.pricing(process, format, "turnaround_max_d"),
          from: max,
          to: null,
        });
    }
  }
}

function diffScanners(initial: LabDraft, current: LabDraft, push: Push): void {
  const models = new Set([
    ...Object.keys(initial.scanners),
    ...Object.keys(current.scanners),
  ]);
  for (const model of models) {
    push(
      labPath.scanner(model),
      initial.scanners[model] === true,
      current.scanners[model] === true,
    );
  }
}

/** Only cells whose process survives — a dropped one is diffProcesses' business. */
function diffPricing(initial: LabDraft, current: LabDraft, push: Push): void {
  for (const { process, format, key } of CELL_KEYS) {
    if (current.processes[process] !== true) continue;

    const was = initial.pricing[key] ?? { price: "", turnaround: "" };
    const now = current.pricing[key] ?? { price: "", turnaround: "" };

    push(
      labPath.pricing(process, format, "price_thb"),
      parsePrice(was.price),
      parsePrice(now.price),
    );

    const before = parseTurnaround(was.turnaround);
    const after = parseTurnaround(now.turnaround);
    push(
      labPath.pricing(process, format, "turnaround_min_d"),
      before.min,
      after.min,
    );
    push(
      labPath.pricing(process, format, "turnaround_max_d"),
      before.max,
      after.max,
    );
  }
}

function diffServices(initial: LabDraft, current: LabDraft, push: Push): void {
  const keys = new Set([
    ...Object.keys(initial.services),
    ...Object.keys(current.services),
  ]);
  for (const key of keys) {
    const was = initial.services[key] ?? { on: false, note: "" };
    const now = current.services[key] ?? { on: false, note: "" };
    push(labPath.curatedService(key, "offered"), was.on, now.on);
    // A note on a service nobody offers is not a note; it goes with the box.
    push(
      labPath.curatedService(key, "note"),
      was.on ? textOrNull(was.note) : null,
      now.on ? textOrNull(now.note) : null,
    );
  }

  diffCustomRows(
    initial.customServices,
    current.customServices,
    (id) => labPath.customService(id, "custom_label"),
    push,
    (id) => labPath.customService(id, "note"),
  );
}

function diffSupplies(initial: LabDraft, current: LabDraft, push: Push): void {
  const keys = new Set([
    ...Object.keys(initial.supplies),
    ...Object.keys(current.supplies),
  ]);
  for (const key of keys) {
    push(
      labPath.curatedSupply(key),
      initial.supplies[key] === true,
      current.supplies[key] === true,
    );
  }

  diffCustomRows(
    initial.customSupplies,
    current.customSupplies,
    (id) => labPath.customSupply(id),
    push,
  );
}

/**
 * A contributor's own rows, which are addressed by the id the form gave them.
 *
 * Removal is `label → null` rather than an absence, which is what makes adding,
 * renaming and removing the same three shapes as every other leaf.
 */
function diffCustomRows(
  initial: DraftCustom[],
  current: DraftCustom[],
  labelPath: (id: string) => string,
  push: Push,
  notePath?: (id: string) => string,
): void {
  const before = new Map(initial.map((row) => [row.id, row]));
  const after = new Map(current.map((row) => [row.id, row]));

  for (const id of new Set([...before.keys(), ...after.keys()])) {
    const was = before.get(id);
    const now = after.get(id);
    push(
      labelPath(id),
      was ? textOrNull(was.label) : null,
      now ? textOrNull(now.label) : null,
    );
    if (notePath) {
      push(
        notePath(id),
        was ? textOrNull(was.note ?? "") : null,
        now ? textOrNull(now.note ?? "") : null,
      );
    }
  }
}

function diffContacts(initial: LabDraft, current: LabDraft, push: Push): void {
  const before = new Map(initial.contacts.map((c) => [c.id, c]));
  const after = new Map(current.contacts.map((c) => [c.id, c]));

  for (const id of new Set([...before.keys(), ...after.keys()])) {
    const was = before.get(id);
    const now = after.get(id);

    // A removed contact is one leaf, not three: `value → null` deletes the row,
    // and a channel on a row that no longer exists says nothing.
    if (was && !now) {
      push(labPath.contact(id, "value"), was.value, null);
      continue;
    }
    if (!now) continue;

    push(labPath.contact(id, "channel"), was?.channel ?? null, now.channel);
    push(
      labPath.contact(id, "value"),
      was?.value ?? null,
      textOrNull(now.value),
    );
    push(
      labPath.contact(id, "position"),
      was ? initial.contacts.indexOf(was) : null,
      current.contacts.indexOf(now),
    );
  }
}

function diffStock(initial: LabDraft, current: LabDraft, push: Push): void {
  const before = new Map(initial.stock.map((s) => [s.filmStockId, s]));
  const after = new Map(current.stock.map((s) => [s.filmStockId, s]));

  for (const id of new Set([...before.keys(), ...after.keys()])) {
    push(
      labPath.stock(id),
      before.get(id)?.formats ?? null,
      after.get(id)?.formats ?? null,
    );
  }
}

// ---------------------------------------------------------------------------
// Creation, which takes a document rather than a diff
// ---------------------------------------------------------------------------

/** The draft as `createLab` wants it. Empty fields are dropped, not sent as "". */
export function draftToCreateInput(draft: LabDraft) {
  const pricing = CELL_KEYS.flatMap(({ process, format, key }) => {
    if (draft.processes[process] !== true) return [];
    const cell = draft.pricing[key];
    if (!cell) return [];
    const priceThb = parsePrice(cell.price);
    const { min, max } = parseTurnaround(cell.turnaround);
    if (priceThb === null && min === null) return [];
    return [
      { process, format, priceThb, turnaroundMinD: min, turnaroundMaxD: max },
    ];
  });

  return {
    nameEn: draft.nameEn.trim(),
    nameTh: textOrNull(draft.nameTh),
    location: draft.location!,
    areaEn: textOrNull(draft.areaEn),
    areaTh: textOrNull(draft.areaTh),
    street: textOrNull(draft.street),
    landmarkNote: textOrNull(draft.landmarkNote),
    status: draft.status,
    statusNote: textOrNull(draft.statusNote),
    hours: draft.hours ?? undefined,
    processes: CHEM_PROCESSES.filter((p) => draft.processes[p] === true),
    scanners: Object.keys(draft.scanners).filter((m) => draft.scanners[m]),
    pricing,
    services: [
      ...Object.entries(draft.services)
        .filter(([, v]) => v.on)
        .map(([key, v]) => ({ key, note: textOrNull(v.note) })),
      ...draft.customServices
        .filter((s) => s.label.trim() !== "")
        .map((s) => ({
          customLabel: s.label.trim(),
          note: textOrNull(s.note ?? ""),
        })),
    ],
    supplies: [
      ...Object.keys(draft.supplies)
        .filter((k) => draft.supplies[k])
        .map((key) => ({ key })),
      ...draft.customSupplies
        .filter((s) => s.label.trim() !== "")
        .map((s) => ({ customLabel: s.label.trim() })),
    ],
    contacts: draft.contacts
      .filter((c) => c.value.trim() !== "")
      .map((c) => ({ id: c.id, channel: c.channel, value: c.value.trim() })),
    stock: draft.stock.map((s) => ({
      filmStockId: s.filmStockId,
      formats: s.formats,
    })),
  };
}

/** The create gate, so the button can be disabled rather than the save refused. */
export function createGate(draft: LabDraft): {
  ready: boolean;
  missing: string[];
} {
  const missing: string[] = [];
  if (draft.nameEn.trim() === "") missing.push("a name");
  if (draft.location === null) missing.push("a pin on the map");
  if (!CHEM_PROCESSES.some((p) => draft.processes[p] === true)) {
    missing.push("at least one process");
  }
  return { ready: missing.length === 0, missing };
}

export { CHEM_PROCESSES, CONTACT_CHANNELS, FILM_FORMATS };
