-- Moved.
--
-- This file was the design-stage schema. It is now the first migration, at
-- db/migrations/0000_init.sql, applied by drizzle-kit — one copy, so the two
-- cannot drift.
--
-- lib/db/schema.ts mirrors that migration and is the source of inferred types
-- for every query. Nothing generates one from the other, so a migration and
-- the schema file change in the same pull request.
--
-- The rationale for what the schema enforces is in docs/00_BACKLOG.md,
-- Pillar 2. The rules themselves are asserted by
-- tests/db/schema-invariants.test.ts.
